version: '3.4'

services:
  SqlServerDb:
    container_name: SqlServerContainer
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=changeMe123
    networks:
      - myAppNetwork

  WebApi:
    container_name: WebApiContainer
    image: ${DOCKER_REGISTRY-}codenamepropono.server
    ports:
      - 8001:80
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - SqlServerDb
    networks:
      - myAppNetwork

networks:
  myAppNetwork: